name: Run Postman Tests + Generate Swagger

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'openapi.yaml'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: |
          newman run collection.json -e utho-environment.json

      - name: Convert to OpenAPI YAML
        run: |
          npx postman-to-openapi collection.json -f openapi.yaml

      - name: Commit Swagger file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add openapi.yaml
          git diff --cached --quiet || git commit -m "Update OpenAPI spec"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git