name: Run Postman Tests + Generate Swagger

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install tools
        run: |
          npm install -g newman
          npm install -g postman-to-openapi

      - name: Run Postman tests
        run: |
          newman run collection.json -e utho-environment.json

      - name: Convert to OpenAPI YAML
        run: |
          postman-to-openapi collection.json -f openapi.yaml

      - name: Commit Swagger file
        run: |
          git config --global user.name "gopaluthocloud"
          git config --global user.email "gopal.s@utho.com"
          git add openapi.yaml
          git commit -m "Update OpenAPI spec" || echo "No changes"
          git push